# Generated by Django 3.2.12 on 2023-03-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagem',
            field=models.ImageField(upload_to='%Y/%m', verbose_name='Image'),
        ),
    ]
