# Generated by Django 3.2.12 on 2023-03-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_itemmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmenu',
            name='item_menu_pai',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.itemmenu', verbose_name='Item Menu Pai'),
            preserve_default=False,
        ),
    ]
