# Generated by Django 3.2.12 on 2023-03-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20230329_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='dominio_oficial',
            field=models.CharField(max_length=100, null=True, verbose_name='Domínio Oficial'),
        ),
    ]
