# Generated by Django 3.2.12 on 2023-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, null=True, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(max_length=200, verbose_name="Descrição"),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
    ]
