# Generated by Django 3.2.12 on 2023-03-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_smtp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("codigo", models.CharField(max_length=100, verbose_name="Codígo")),
                ("pagina", models.ManyToManyField(to="home.Pagina")),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
            },
        ),
    ]
