# Generated by Django 3.2.12 on 2023-03-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Label")),
                ("link", models.CharField(max_length=100, verbose_name="Link")),
                ("order", models.IntegerField(verbose_name="Order")),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.menu",
                        verbose_name="Menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item menu",
                "verbose_name_plural": "Items menu",
            },
        ),
    ]
