# Generated by Django 3.2.12 on 2023-03-07 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_itemmenu_item_menu_pai"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmenu",
            name="item_menu_pai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.itemmenu",
                verbose_name="Item Menu Pai",
            ),
        ),
    ]
