# Generated by Django 3.2.12 on 2023-03-07 14:43

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20230307_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_fundo', models.ImageField(upload_to='assets', verbose_name='Imagem Fundo')),
                ('video_fundo', models.FileField(upload_to='assets', verbose_name='Video Fundo')),
                ('logo', models.FileField(upload_to='assets', verbose_name='Logo')),
                ('background_cor1', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='Background Cor 1')),
                ('background_cor2', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='Background Cor 2')),
                ('link_telefone', models.CharField(max_length=100, verbose_name='Link Telefone')),
                ('link_whatsapp', models.CharField(max_length=100, verbose_name='Link Whatsapp')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenção',
            },
        ),
    ]
