# Generated by Django 3.2.12 on 2023-03-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_site_indexavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='indexavel',
            field=models.BooleanField(default=True, verbose_name='Indexável?'),
        ),
    ]
