# Generated by Django 3.2.12 on 2023-10-11 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0031_auto_20230808_1225"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={
                "verbose_name": "Site",
                "verbose_name_plural": "Configurações Básicas",
            },
        ),
    ]
