# Generated by Django 3.2.12 on 2024-10-21 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0032_alter_site_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Imagem')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Atualização')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_atualizacao_experiencia', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Atualização')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_criacao_experiencia', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
            ],
            options={
                'verbose_name': 'Experiência Exclusiva',
                'verbose_name_plural': 'Experiências Exclusivas',
            },
        ),
        migrations.CreateModel(
            name='EventoEFesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Imagem')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Atualização')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_atualizacao_evento_festa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Atualização')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_criacao_evento_festa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
            ],
            options={
                'verbose_name': 'Evento e Festa',
                'verbose_name_plural': 'Eventos e Festas',
            },
        ),
    ]
