# Generated by Django 3.2.12 on 2024-11-04 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0032_alter_site_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo Principal')),
                ('titulo_artigo', models.CharField(max_length=255, verbose_name='Titulo Artigo')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('link_externo', models.URLField(blank=True, verbose_name='Link Externo')),
                ('imagem_capa', models.ImageField(upload_to='imagens/')),
                ('data', models.DateField(verbose_name='Data')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Atualização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_atualizacao_titulo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Atualização')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_criacao_titulo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
            ],
            options={
                'verbose_name': 'Seção Artigo',
                'verbose_name_plural': 'Seções Artigos',
            },
        ),
    ]
