# Generated by Django 3.2.12 on 2024-07-19 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0036_auto_20240719_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmenu',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de atualização'),
        ),
        migrations.AddField(
            model_name='itemmenu',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='itemmenu',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_atualizacao_item_menu', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Atualização'),
        ),
        migrations.AddField(
            model_name='itemmenu',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_criacao_item_menu', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação'),
        ),
    ]
