#!/usr/bin/env sh
# https://typicode.github.io/husky/
. "$(dirname -- "$0")/_/husky.sh"
export PS1="\[\e[31m\]\d \t\[\e[0m\]\s-\v\$ "
echo '⚡ Hook pre-commit'

rm -f yarn.lock
rm -f yarn-error.log
rm -f package-lock.json

yarn build

echo '🟢 Finalizado'


